http:
  routers:
    omada:
      entryPoints:
        - websecure
      rule: "Host(`omada.example.com`)"
      middlewares:
        - "default-headers"
      tls: {}
      service: omada

    portainer:
      entryPoints:
        - websecure
      rule: "Host(`portainer.example.com`)"
      service: portainer
      middlewares:
        # - "forwardAuth-authentik"
        - "default-headers"

  services:
    omada:
      loadBalancer:
        servers:
          - url: https://10.0.12.10:8043
        passHostHeader: true

    portainer:
      loadBalancer:
        servers:
          - url: https://10.0.11.13:9443/
        passHostHeader: true
