---
# Start VMs
- name: Start VMs
  community.general.proxmox_kvm:
    api_user: "{{ pve_ansible_user_api_realm }}"
    api_token_id: "{{ pve_ansible_token_id }}"
    api_token_secret: "{{ lookup('file', api_token_file_path) }}"
    api_host: "{{ pve_primary_node }}"

    # node: '{{item.node}}'
    vmid: "{{ item.value.vmid }}"
    name: "{{ item.key }}"
    state: "started"
  loop: "{{ vm_config | dict2items }}"
  loop_control:
    pause: 5
    label: "{{ item.key }}"
  when: created_pve_vm is succeeded and inventory_hostname == pve_primary_node and item.value.state == "new"
  delegate_to: "{{ pve_primary_node }}"
