http:
  routers:
    traefik-dashboard:
      rule: "Host(`traefik.example.com`)"
      service: api@internal
      entryPoints:
        - websecure
      middlewares: "default-headers"
      tls:
        options: "modern"
