services:
  dns1:
    container_name: dns1
    hostname: dns1.example.com
    image: technitium/dns-server:latest
    user: 1000:1000
    security_opt:
      - no-new-privileges:true
    volumes:
      - /opt/docker-data/dns1:/etc/dns
    restart: always
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
    networks:
      gateway_vlan:
        ipv4_address: 10.53.53.53
    labels:
      traefik.enable: true
      traefik.docker.network: proxy # Used for Traefik to find the container while Technitium is exposed on a different network
      traefik.http.routers.dns1.entrypoints: websecure
      traefik.http.services.dns1.loadbalancer.server.port: 5380
      traefik.http.routers.dns1.rule: Host(`dns1.example.com`)
      traefik.http.routers.dns1.middlewares: default-headers@file

    environment:
      - DNS_SERVER_DOMAIN=dns1.example.com #The primary domain name used by this DNS Server to identify itself.

networks:
  gateway_vlan:
    external: true
