- name: Delete virtual machines hosted on proxmox
  hosts: pve1 # Group of hosts. I put the primary_node for clusters
  roles:
    - pve_delete_vm
  vars:
    node: "pve1" # Ensure this matches your actual node name
    vmids:
      - 1500
