vm_config:
  home-assistant:
    vm_image_name: haos_ova-14.1.qcow2.xz
    vm_image_url: https://github.com/home-assistant/operating-system/releases/download/14.1/haos_ova-14.1.qcow2.xz
    # Compute
    name: "home-assistant"
    vmid: "100"
    node: "pve01"
    memory: 4096
    cores: 4
    tags: 
      - automation
      - home-assistant
      - iot
    # Networking
    net:
      net0: "virtio,bridge=vnet50" # the main vlan interface
      net1: "virtio,bridge=vnet51" # this interface can be connected to the same IOT/CCTV network so you need to play with firewall rules and keep the vlan totally closed
    ipconfig:
      # ipconfig0: "ip=dhcp"
      ipconfig0: "ip=10.0.50.10/28,gw=10.0.50.1"
      ipconfig1: "ip=10.0.51.10/16,gw=10.0.51.1" # for some reasons these values are not used
    # Storage
    bootdisk: "scsi0"
    disk: "scsi0"
    size: "32G"
    scsihw: "virtio-scsi-pci"
    storage: "local-lvm"
    scsi:
      scsi0: "local-lvm:0,import-from=local:0/haos_ova-14.1.qcow2,format=qcow2"

    bios: ovmf  # Use OVMF (EFI)
    efidisk0: # EFI disk configuration as the VM uses UEFI
      storage: local-lvm
      format: raw
      efitype: 4m  
      pre_enrolled_keys: false

    # Other VM Configuration
    agent: "enabled=1"
    onboot: true
    state: new
