vm_config:
  ubuntu-docker-host-01:
    vm_image_name: noble-server-cloudimg-amd64.qcow2
    vm_image_url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
  
    # Compute
    name: "ubuntu-docker-host-01"
    vmid: "10001"
    node: "pve01"
    memory: 4096
    cores: 4
    tags: 
      - networking
      - ubuntu
      - docker
    # Networking
    net:
      net0: "virtio,bridge=vmbr1"
      net1: "virtio,bridge=vnet20" # Will be ens19 on the vm
      net2: "virtio,bridge=vnet3" # ens20
      net3: "virtio,bridge=vnet800" #ens21
    ipconfig:
      # ipconfig0: "ip=dhcp"
      ipconfig0: "ip=10.0.0.10/24,gw=10.0.0.1"
    # Cloud-init configuration
    citype: "nocloud"
    cicustom: "user=local:snippets/ubuntu-docker-host-01.yml"
    cloud_init_template: "docker-host.j2"
    cloud_init_template_name: "ubuntu-docker-host-01.yml"
    # Storage
    bootdisk: "scsi0"
    disk: "scsi0"
    size: "32G"
    scsihw: "virtio-scsi-pci"
    storage: "local-lvm"
    scsi:
      scsi0: "local-lvm:0,import-from=local:0/noble-server-cloudimg-amd64.qcow2,format=qcow2"
    ide:
      ide2: "local-lvm:cloudinit"

    # Other VM Configuration
    agent: "enabled=1"
    onboot: true
    state: new # This is to indicate if the virtual machine needs to be created or already exists in Proxmox. It needs to be manually definded.