---
- name: Update and upgrade all packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Remove existing Docker packages
  ansible.builtin.apt:
    name: "{{ docker_pkgs }}"
    state: absent
    cache_valid_time: 0 # Ensure removal regardless of cache

- name: Install dependencies for Docker
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg2

- name: Create directory for Docker's GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64
      signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    filename: docker
    state: present

- name: Install desired Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

# # Additional Docker hardening tasks (consider these based on your needs):
- name: Create a dedicated Docker group for managing containers
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to the Docker group for non-root management
  ansible.builtin.user:
    name: "{{ vm_ansible_user }}" # Adjust username as needed
    groups: docker
    append: true

# I need to fix something related to the daemon as it's breaking the daemon and blocker docker from starting
# - name: Configure Docker daemon options for enhanced security
#   ansible.builtin.template:
#     src: docker-daemon.j2
#     dest: /etc/docker/daemon.json
#     owner: root
#     group: root
#     mode: "0600"
#   notify: Restart docker
