services:
  traefik:
    image: traefik:v3.2
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      service_restricted_vlan:
        ipv4_address: 10.0.1.10
      proxy:

    volumes:
      - /opt/docker-data/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /opt/docker-data/traefik/dynamic:/dynamic:ro
      - /mnt/nfs/letsencrypt/:/letsencrypt/:ro
    environment:
      - DOCKER_HOST=docker-socket-proxy
    depends_on:
      - docker-socket-proxy

  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker-socket-proxy
    restart: always
    networks:
      - proxy
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - NETWORKS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  proxy:
    external: true
    internal: true
  service_restricted_vlan:
    external: true