vm_config:
  ubuntu-docker-host-test-01:
    vm_image_name: noble-server-cloudimg-amd64.qcow2
    vm_image_url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img

    # Compute
    name: "ubuntu-docker-host-test-01"
    vmid: "9999"
    node: "pve03"
    memory: 4096
    cores: 4

    # Networking
    net:
      net0: "virtio,bridge=vlan199"
    ipconfig:
      # ipconfig0: "ip=dhcp"
      ipconfig0: "ip=10.0.199.10/2,gw=10.0.199.1"

    # Cloud-init configuration
    citype: "nocloud"
    cicustom: "user=local:snippets/ubuntu-docker-host-test-01.yml"
    cloud_init_template: "docker-host.j2"
    cloud_init_template_name: "ubuntu-docker-host-test-01.yml"
    # Storage
    bootdisk: "scsi0"
    disk: "scsi0"
    size: "32G"
    scsihw: "virtio-scsi-pci"
    storage: "local-lvm"
    scsi:
      scsi0: "local-lvm:0,import-from=local:0/noble-server-cloudimg-amd64.qcow2,format=qcow2"
    ide:
      ide2: "local-lvm:cloudinit"

    # Other VM Configuration
    agent: "enabled=1"
    onboot: true
    state: present # Manually set to indicate that virtual machine already exists in the proxmox cluster/node and should not be created/stopped in some playbooks
