---
- name: Update hosts ( Debian based )
  when: ansible_os_family == 'Debian'
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: true
        autoclean: true

    - name: Check if reboot is required - Debian
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      ignore_errors: true
      changed_when: true
      notify: Reboot host

  rescue:
    - name: Display error message for Debian update failure
      ansible.builtin.debug:
        msg: "Failed to update Debian based host. Please check logs."

- name: Update hosts ( RedHat based )
  when: ansible_os_family == 'RedHat'
  block:
    - name: Update dnf cache
      ansible.builtin.dnf:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade packages
      ansible.builtin.dnf:
        upgrade: all

    - name: Check if reboot is required - RedHat
      ansible.builtin.command:
        cmd: needs-restarting -r -s
      register: reboot_required_command
      failed_when: reboot_required_command.rc > 1
      changed_when: reboot_required_command.rc == 1
      notify: Reboot host

  rescue:
    - name: Display error message for RedHat update failure
      ansible.builtin.debug:
        msg: "Failed to update RedHat based host. Please check logs."
