# ---
---
- name: Join_cluster_init
  when: inventory_hostname != pve_primary_node
  block:
    - name: Identify the SSH public key and SSH addresses of initial cluster host
      ansible.builtin.set_fact:
        _pve_cluster_host_key: "{{ ' '.join((hostvars[pve_primary_node]._pve_ssh_public_key.content | b64decode).split()[:-1]) }}"
        _pve_cluster_host_addresses: "{{ hostvars[pve_primary_node].ansible_host }}"

    - name: Temporarily mark that cluster host as known in root user's known_hosts
      ansible.builtin.blockinfile:
        dest: /root/.ssh/known_hosts
        create: true
        mode: "0600"
        marker: "# {mark}: cluster host key for joining"
        content: "{{ _pve_cluster_host_addresses }} {{ _pve_cluster_host_key }}"

# Step 4: Add node to Proxmox cluster
- name: Add node to Proxmox cluster
  ansible.builtin.command: pvecm add {{ hostvars[pve_primary_node].ansible_host }} -use_ssh
  when: inventory_hostname != pve_primary_node
  throttle: 1
  args:
    creates: "{{ pve_cluster_conf }}"

- name: Remove the cluster host's public key from root user's known_hosts
  ansible.builtin.blockinfile:
    dest: /root/.ssh/known_hosts
    state: absent
    mode: "0600"
    marker: "# {mark}: cluster host key for joining"
  when: inventory_hostname != pve_primary_node
