services:
  portainer-ce:
    ports:
      - "9443:9443"
    container_name: portainer
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/docker-data/portainer:/data"
    image: "portainer/portainer-ce:latest"
    networks:
      - proxy

networks:
  proxy:
    external: true
